/*
 * Copyright 2025 patryk3211
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.patryk3211.powergrid.kinetics.motor;

/**
 * Runtime state of a DC motor.
 *
 * This class intentionally contains no Minecraft or Create classes.
 * It can therefore be used by the motor simulation independently
 * from the block entity.
 */
public final class MotorState {

    /**
     * Terminal voltage applied to the motor.
     */
    private double voltage;

    /**
     * Armature current.
     */
    private double current;

    /**
     * Back electromotive force.
     */
    private double backEmf;

    /**
     * Electromagnetic torque generated by the motor.
     */
    private double electromagneticTorque;

    /**
     * External mechanical load torque.
     */
    private double loadTorque;

    /**
     * Friction torque.
     */
    private double frictionTorque;

    /**
     * Net mechanical torque.
     */
    private double netTorque;

    /**
     * Angular velocity in rad/s.
     */
    private double angularVelocity;

    /**
     * Mechanical acceleration in rad/s^2.
     */
    private double angularAcceleration;

    /**
     * Current RPM.
     */
    private double rpm;

    /**
     * Electrical input power.
     */
    private double electricalPower;

    /**
     * Mechanical output power.
     */
    private double mechanicalPower;

    /**
     * Copper loss.
     */
    private double copperLoss;

    /**
     * Approximate motor temperature.
     *
     * The actual thermal simulation can later be connected to
     * PowerGrid's ThermalBehaviour.
     */
    private double temperature;

    public double voltage() {
        return voltage;
    }

    public void voltage(double voltage) {
        this.voltage = voltage;
    }

    public double current() {
        return current;
    }

    public void current(double current) {
        this.current = current;
    }

    public double backEmf() {
        return backEmf;
    }

    public void backEmf(double backEmf) {
        this.backEmf = backEmf;
    }

    public double electromagneticTorque() {
        return electromagneticTorque;
    }

    public void electromagneticTorque(double electromagneticTorque) {
        this.electromagneticTorque = electromagneticTorque;
    }

    public double loadTorque() {
        return loadTorque;
    }

    public void loadTorque(double loadTorque) {
        this.loadTorque = loadTorque;
    }

    public double frictionTorque() {
        return frictionTorque;
    }

    public void frictionTorque(double frictionTorque) {
        this.frictionTorque = frictionTorque;
    }

    public double netTorque() {
        return netTorque;
    }

    public void netTorque(double netTorque) {
        this.netTorque = netTorque;
    }

    public double angularVelocity() {
        return angularVelocity;
    }

    public void angularVelocity(double angularVelocity) {
        this.angularVelocity = angularVelocity;
    }

    public double angularAcceleration() {
        return angularAcceleration;
    }

    public void angularAcceleration(double angularAcceleration) {
        this.angularAcceleration = angularAcceleration;
    }

    public double rpm() {
        return rpm;
    }

    public void rpm(double rpm) {
        this.rpm = rpm;
    }

    public double electricalPower() {
        return electricalPower;
    }

    public void electricalPower(double electricalPower) {
        this.electricalPower = electricalPower;
    }

    public double mechanicalPower() {
        return mechanicalPower;
    }

    public void mechanicalPower(double mechanicalPower) {
        this.mechanicalPower = mechanicalPower;
    }

    public double copperLoss() {
        return copperLoss;
    }

    public void copperLoss(double copperLoss) {
        this.copperLoss = copperLoss;
    }

    public double temperature() {
        return temperature;
    }

    public void temperature(double temperature) {
        this.temperature = temperature;
    }

    /**
     * Resets all dynamic values while retaining the object itself.
     */
    public void reset() {
        voltage = 0;
        current = 0;
        backEmf = 0;
        electromagneticTorque = 0;
        loadTorque = 0;
        frictionTorque = 0;
        netTorque = 0;
        angularVelocity = 0;
        angularAcceleration = 0;
        rpm = 0;
        electricalPower = 0;
        mechanicalPower = 0;
        copperLoss = 0;
        temperature = 0;
    }
}